server:
  port: 7000

spring:
  cloud:
    config:
      server:
        svn:
          uri: https://subversion.assembla.com/svn/spring-cloud-config-repo/
#        git:
#          uri: https://github.com/spring-cloud-samples/config-repo/
  profiles:
    active: subversion

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.cloud.config.server: DEBUG
